Backend config
archimatchproject/backend pull request #6
Opened 2024-06-19 10:05 UTC by ahmedhamilastage

-isort conf 
-doctsring 
-environ replace decouple
-precommit

2024-06-19 11:43 UTC, MohamedMegdich1 commented on app/users/services/__init__.py
remove this

2024-06-19 11:43 UTC, MohamedMegdich1 commented on app/users/serializers/__init__.py
remove this

2024-06-19 11:43 UTC, MohamedMegdich1 commented on app/users/models/__init__.py
remove this

2024-06-19 11:43 UTC, MohamedMegdich1 commented on app/users/controllers/__init__.py
remove this

2024-06-19 11:43 UTC, MohamedMegdich1 commented on app/users/admin/__init__.py
remove this

2024-06-19 11:43 UTC, MohamedMegdich1 commented on app/cms/serializers/__init__.py
remove this

2024-06-19 11:43 UTC, MohamedMegdich1 commented on app/cms/models/__init__.py
remove this

2024-06-19 11:43 UTC, MohamedMegdich1 commented on app/announcement/serializers/__init__.py
remove this

2024-06-19 11:43 UTC, MohamedMegdich1 commented on app/announcement/models/__init__.py
remove this

2024-06-19 11:43 UTC, MohamedMegdich1 commented on app/announcement/controllers/__init__.py
remove this

2024-06-19 11:43 UTC, MohamedMegdich1 commented on app/announcement/admin/__init__.py
remove this

2024-06-19 12:49 UTC, ahmedhamilastage commented on app/announcement/admin/utils/ProjectImageAdmin.py
> +    list_display = ("id", "id", "image")
fixed in last commit

2024-06-20 08:07 UTC, MohamedMegdich1 requested changes

2024-06-20 08:07 UTC, MohamedMegdich1 commented on app/users/controllers/ArchimatchUserViewSet.py
>  class ArchimatchUserViewSet(viewsets.ModelViewSet):
why using ModelViewSet change it

2024-06-20 08:07 UTC, MohamedMegdich1 commented on app/users/controllers/ClientViewSet.py
> +        methods=["post"],
uppercase

2024-06-20 08:07 UTC, MohamedMegdich1 commented on app/cms/urls.py
> +from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
why importing this ?

2024-06-20 08:07 UTC, MohamedMegdich1 commented on app/cms/urls.py
> +router.register("blog", BlogViewSet, basename="blog")
Please remember the following text: "Represent routes in a tree."

2024-06-20 08:07 UTC, MohamedMegdich1 commented on app/cms/serializers/__init__.py
> +from app.cms.serializers.BlogSerializer import BlogSerializer
remove this

2024-06-20 08:07 UTC, MohamedMegdich1 commented on app/cms/serializers/SliderImageSerializer.py
>  class SliderImageSerializer(serializers.ModelSerializer):
add docstring

2024-06-20 08:07 UTC, MohamedMegdich1 commented on app/cms/serializers/BlockSerializer.py
> +class BlockSerializer(serializers.ModelSerializer):
add docstring

2024-06-20 08:07 UTC, MohamedMegdich1 commented on app/cms/controllers/__init__.py
> +from .BlogViewSet import BlogViewSet
remove this

2024-06-20 08:07 UTC, MohamedMegdich1 commented on app/cms/admin/BlogAdmin.py
>  class BlogAdmin(admin.ModelAdmin):
docstring

2024-06-20 10:15 UTC, MohamedMegdich1 approved these changes

2024-06-20 10:15 UTC, merged